#!/bin/bash

# malum biz cevo@cevdetabbas.com ile login oldugumuzdan kelli bu drive mevzuulari bayaa bir karismakta o sebepten zaar

# bu normal ve One drive folderlari birbirine sysncleyecek bi komut lazim ve elzem
